#!/bin/sh
### BEGIN INIT INFO
# Provides:          reboot
# Required-Start:
# Required-Stop:
# Default-Start:
# Default-Stop:      6
# Short-Description: Execute the reboot command.
# Description:
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin

if [ -x /usr/sbin/kexec ]
then
  echo -n "kexec: "
  /usr/sbin/kexec -e -i -x
fi
echo -n "Rebooting... "
reboot SED_HALTARGS
