# Small systemd based distro with X11 support for graphical environments

DISTRO_VERSION = "topic-x11.0"

require topic-systemd-common.inc

# Add x11 and other features to create a GUI image (desktop or otherwise)
DISTRO_FEATURES_DEFAULTS += "touchscreen mouse keyboard x11 pam opengl usrmerge pulseaudio"

